const Data = {
  categories: [
    {
      name: 'Burgers',
      items: [
        {
          img: require('../../../Assets/Burger1.png'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/Burger2.png'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/Burger3.png'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/Burger4.png'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f5.gif'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/f6.gif'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/f7.gif'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/f8.gif'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    },
    {
      name: 'Desserts',
      items: [
        {
          img: require('../../../Assets/Desert1.png'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/Desert2.png'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/Desert3.png'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/Desert4.png'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/Desert5.png'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/Desert6.png'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/Desert7.png'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/Desert8.png'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    }, {
      name: 'Drinks',
      items: [
        {
          img: require('../../../Assets/Drinks1.png'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/Drinks2.png'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/Drinks3.png'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/Drinks4.png'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f5.gif'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/f6.gif'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/f7.gif'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/f8.gif'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    }, {
      name: 'Pasta',
      items: [
        {
          img: require('../../../Assets/Pasta1.gif'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/Pasta2.gif'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/Pasta3.png'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/Pasta4.png'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f5.gif'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/f6.gif'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/f7.gif'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/f8.gif'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    }, {
      name: 'Pizzas',
      items: [
        {
          img: require('../../../Assets/f1.gif'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f2.gif'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/f3.gif'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/f4.gif'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f5.gif'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/f6.gif'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/f7.gif'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/f8.gif'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    }, {
      name: 'Salads',
      items: [
        {
          img: require('../../../Assets/Salads1.gif'),
          Text: 'MARGHERITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/Salads2.gif'),
          Text: 'VINCENT',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.00',
        },
        {
          img: require('../../../Assets/Salads3.png'),
          Text: 'PEPPERONI',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.90',
        },
        {
          img: require('../../../Assets/Salads4.png'),
          Text: 'DIABLO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f5.gif'),
          Text: 'CARBONARA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.80',
        },
        {
          img: require('../../../Assets/f6.gif'),
          Text: 'CAPRICCIOSA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.70',
        },
        {
          img: require('../../../Assets/f7.gif'),
          Text: 'PROSCIUTTO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.20',
        },
        {
          img: require('../../../Assets/f8.gif'),
          Text: 'SAPORITA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f9.gif'),
          Text: 'CALZONE',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.60',
        },
        {
          img: require('../../../Assets/f10.gif'),
          Text: 'NEAPOLITANO',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.80',
        },
        {
          img: require('../../../Assets/f11.gif'),
          Text: 'TARANTELLA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$3.60',
        },
        {
          img: require('../../../Assets/f12.gif'),
          Text: 'FORTEZZA',
          Para: 'Classic marinara sauce, authentic old-world pepperoni, all-natural...',
          Price: '$2.40',
        },
      ],
    },
  ],
};

export default Data;
